server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: auth-service

# -- MySQl ---
  #datasource:
    #url: ${DB_URL}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    #driver-class-name: com.mysql.cj.jdbc.Driver

#-- PostgreSQL --

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect ✅


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  # ✅ FIXED REDIS (IMPORTANT)
  data:
    redis:
      url: ${REDIS_URL}
      timeout: 2000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  thymeleaf:
    check-template-location: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

app:
  email:
    from: ${SENDER_MAIL}
    from-name: ${APP_NAME}

otp:
  expiry-minutes: 10
  reset-token-expiry-minutes: 5

rate:
  limit:
    enabled: false

    global:
      tokens: 200
      refillMinutes: 1
      refillHours: 0

    authSensitive:
      tokens: 5
      refillMinutes: 1
      refillHours: 0

    otpFlow:
      tokens: 3
      refillMinutes: 10
      refillHours: 0

    passwordOps:
      tokens: 5
      refillMinutes: 10
      refillHours: 0

    accountDelete:
      tokens: 3
      refillMinutes: 0
      refillHours: 1


logging:
  level:
    com.tracker.auth: INFO
    org.springframework.security: WARN
